update zap full scan output

diff --git a/.github/workflows/security-scan.yaml b/.github/workflows/security-scan.yaml
--- a/.github/workflows/security-scan.yaml
+++ b/.github/workflows/security-scan.yaml
@@ -32,20 +32,24 @@ jobs:
       - run: sleep 8
 
       - name: Run ZAP Full Scan on the accounts website
+        id: zap_scan
         # https://www.zaproxy.org/docs/docker/full-scan/
-        run: docker run
-          --add-host host.docker.internal:host-gateway
-          -v $(pwd):/zap/wrk/:rw
-          -u root
-          -t
-          ghcr.io/zaproxy/zaproxy:stable
-          zap-full-scan.py
-          -t http://host.docker.internal:3000
-          -j
-          -g gen.conf
-          -r accounts.zap-scan-report.html
-          -a || true
-          # || true - force exit code 0 so action continues
+        run: |
+          set +e        
+          docker run \
+          --add-host host.docker.internal:host-gateway \
+          -v $(pwd):/zap/wrk/:rw \
+          -u root \
+          -t \
+          ghcr.io/zaproxy/zaproxy:stable \
+          zap-full-scan.py \
+          -t http://host.docker.internal:3000 \
+          -j \
+          -g gen.conf \
+          -r accounts.zap-scan-report.html \
+          -a
+        EXIT_CODE="$?"
+        echo "EXIT_CODE=$EXIT_CODE" >> $GITHUB_OUTPUT
 
       - name: Run Dastardly scan on accounts website
         # https://portswigger.net/burp/documentation/dastardly/generic
@@ -78,25 +82,30 @@ jobs:
 
       - name: Run ZAP Full Scan on the demo website
         # https://www.zaproxy.org/docs/docker/full-scan/
-        run: docker run
-          --add-host host.docker.internal:host-gateway
-          -v $(pwd):/zap/wrk/:rw
-          -t
-          -u root
-          ghcr.io/zaproxy/zaproxy:stable
-          zap-full-scan.py
-          -t http://host.docker.internal:3001
-          -j
-          -g gen.conf
-          -r demo.zap-scan-report.html
-          -a || true
-          # || true - force exit code 0 so action continues
+        run: |
+          set +e       
+          docker run \
+          --add-host host.docker.internal:host-gateway \
+          -v $(pwd):/zap/wrk/:rw \
+          -t \
+          -u root \
+          ghcr.io/zaproxy/zaproxy:stable \
+          zap-full-scan.py \
+          -t http://host.docker.internal:3001 \
+          -j \
+          -g gen.conf \
+          -r demo.zap-scan-report.html \
+          -a
+        EXIT_CODE="$?"
+        echo "EXIT_CODE=$EXIT_CODE" >> $GITHUB_OUTPUT
           
       - name: Upload ZAP Scan Output
         uses: actions/upload-artifact@v3
         with:
           name: zap-scan-output
           path: "*zap-scan-report.html"
+        # Exit with the exit code of the ZAP scan
+      - run: exit "${{ steps.zap_scan.outputs.EXIT_CODE }}"
   
       - name: Convert Accounts Dastardly JUnit XML report to HTML
         uses: pl-strflt/junit-xml-to-html@v1
